# Generated by Django 5.2.8 on 2025-11-26 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('artists', models.JSONField(blank=True, default=list)),
                ('artist_ids', models.JSONField(blank=True, default=list)),
                ('album_image', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('lyric_valence', models.FloatField(blank=True, null=True)),
                ('lyric_energy', models.FloatField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('lyrics_missing', models.BooleanField(default=False)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('soundcloud_url', models.URLField(blank=True, null=True)),
                ('soundcloud_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='soundcloud', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('play', 'Play'), ('skip', 'Skip'), ('save', 'Save')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodWave.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=512, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_total', models.IntegerField(default=0)),
                ('sync_done', models.IntegerField(default=0)),
                ('sync_in_progress', models.BooleanField(default=False)),
                ('avg_acousticness', models.FloatField(blank=True, null=True)),
                ('avg_danceability', models.FloatField(blank=True, null=True)),
                ('avg_energy', models.FloatField(blank=True, null=True)),
                ('avg_valence', models.FloatField(blank=True, null=True)),
                ('top_genres', models.JSONField(blank=True, default=list)),
                ('last_profile_update', models.DateTimeField(blank=True, null=True)),
                ('tracks', models.ManyToManyField(blank=True, related_name='users', to='MoodWave.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='MoodWave.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodWave.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodWave.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodWave.track')),
            ],
            options={
                'unique_together': {('playlist', 'track')},
            },
        ),
    ]
